### ISSUE TITLE
How do I contribute to this gem translation?

### ISSUE THREAD

**Issue by zulhfreelancer** [excid3/receipts#6]
Hi,

I'm using this gem inside my current project it was awesome. I really like it!

I'm thinking to translate this gem to Malay language since I'm Malaysian and I'm native Malay speaker.

Please show me clear 'how to' step-by-step guide to contribute to this gem and translate the strings to Malay?

Thanks!

**Comment by excid3** [comment]
Awesome! So I don't actually have translations setup at all for this gem yet. We probably should start to do that then.

I think the first step will be to take all or most of the strings out and put them into a configuration file so that it can be easily translated like the locales yaml files. Then you would have a good place to write your translations easily.

If you want to take a stab at writing some code to enable those translations for this gem, let me know!

**Comment by zulhfreelancer** [comment]
I'm not familiar with the setup. Can you do the setup and let me know when the yaml file is ready?

**Comment by Dragonicity** [comment]
You can use I18n to set translations for the strings in the receipt in the Charge model receipt method, for example:

```ruby
line_items: [
        [I18n.t(:charge_date), created_at.to_s],
```
This will work for Malay Bahasa, French, etc. but I cannot use it for Chinese.
